language: node_js
node_js:
  - '6'

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    - ENCRYPTION_LABEL: "a8c5e363dc84"
    - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
    - TRIGGER_REPO_SLUG: "patternfly/patternfly-ng"
    - TRIGGER_REPO_BRANCH: "master"

before_install:
  - npm install git+https://github.com/patternfly/patternfly-eng-release.git

install: true

script:
  - sh -x ./node_modules/patternfly-eng-release/scripts/_build.sh -x

after_success:
  - if [[ -s package.json ]]; then cp package.json dist; fi
  - if [[ -s npm-shrinkwrap.json ]]; then cp package.json dist; fi
  - npm prune
  - npm run semantic-release
  - npm run publish-travis

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
