language: node_js
cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '6'

env:
  global:
    - ENCRYPTION_LABEL: "a8c5e363dc84"
    - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
    - TRIGGER_REPO_SLUG: "patternfly/patternfly-ng"
    - TRIGGER_REPO_BRANCH: "master"

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install git+https://github.com/patternfly/patternfly-eng-release.git

install: true

script:
  - sh -x ./node_modules/patternfly-eng-release/scripts/_build.sh -x

before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - npm run publish-travis

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
