language: node_js
node_js:
  - '4'

env:
  global:
    - ENCRYPTION_LABEL: "a8c5e363dc84"
    - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
    - TRIGGER_REPO_SLUG: "patternfly/patternfly-ng"
    - TRIGGER_REPO_BRANCH: "master"

before_install:
  - rvm install 2.3.1
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g bower grunt-cli
  - npm install git+https://github.com/patternfly/patternfly-eng-release.git

install: true

script:
  - sh -x ./node_modules/patternfly-eng-release/scripts/_build.sh -x

after_success:
  - npm run publish-travis
